### ISSUE TITLE
Inside the popped out window same data is not updated

### ISSUE THREAD

**Issue by tposney** [kakaroto/fvtt-module-popout#11]
I have only checked specifically game.user.targets, but this is not updated when a new target is selected by the user from the game screen. 
This makes no sense to me, but I have tried it with no other modules installed, just pop out.

I pop out the actor sheet, and from the original game view target a token, then in the developer console of the popped out sheet check game.user.targets and it is empty. On the developer console of the original scene game.user.targets has the targeted token.

**Comment by tposney** [comment]
I went back to confirm that this is still a problem and for whatever reason I can no longer reproduce. There must be some other condition causing the problem So I will close this and hang my head in shame.

**Comment by kakaroto** [comment]
haha, another Heisenbug! Too many of those lately, the quantum fabric must be dissolving :)
Anyways, popout shouldn't affect the websocket so communication (and entity updates) should work normally. Not sure why it would have failed that time you encountered the issue 🤷
