### ISSUE TITLE
Incompatibility with TokenMold

### ISSUE THREAD

**Issue by pFernbach** [kakaroto/fvtt-module-popout#14]
Hello, I am not able to make this module work if I am also using TokenMold, with pf2e game system. 

The popout correctly open a new window but the window stay black, here are the console output of the popout windows:
```
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. all.min.css:5:54
Éléments correspondant au sélecteur : .fa, .fab, .fad, .fal, .far, .fas
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
Error in parsing value for ‘grid-column’.  Declaration dropped. overlay.css:16:16
Éléments correspondant au sélecteur : #token-mold-overlay .value
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
Error in parsing value for ‘grid-column’.  Declaration dropped. overlay.css:20:16
Éléments correspondant au sélecteur : #token-mold-overlay .icon
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
```

I contacted the author of TokenMold too (no public issues tracker).

**Comment by kakaroto** [comment]
It seems to work fine for me with TokenMold. and I don't see any errors in the console log you pasted other than issues with the token mold css, which shouldn't affect it either.

If you have any more details, or ways to reproduce the problem, feel free to re-open the issue.
