### ISSUE TITLE
pop out more stuff? 

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/fvtt-module-popout#18]
sidebar directories could be popped out maybe.

**Comment by kakaroto** [comment]
Sidebar now get popped out.. any other suggestions ?
maybe macro configs?

**Comment by AE0956** [comment]
> 
> 
> Sidebar now get popped out.. any other suggestions ?
> maybe macro configs?

The Compendium Browser.

**Comment by dennywright** [comment]
AV Windows?

**Comment by seymourbuts** [comment]
Is it possible to add the chatlog as a popout? As it stands you can right-click any of the menu tabs and pop them out except for the chatlog.

**Comment by kakaroto** [comment]
With the latest release, all windows that could be popped out are now popped out, so closing this.

> AV Windows?
I don't think that'd be a good idea to even attempt it honestly, and it might be complicated considering how tight the integration with streaming video has to be.

> Is it possible to add the chatlog as a popout? 
Right clicking the other tabs to pop them into their own windows is a core feature and it doesn't work for chat. Popout module only lets you pop those windows out into their own tabs or browser windows. Nothing I can do about the chat log, but I think Atropos said he was going to make the chat log poppable as well in a future update.
