### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by ebrandi** [kakaroto/fvtt-module-popout#22]
Hi, thks for your effort and your contribution to make these module :)

I`m trying to use it in my server (node.js version) without success :( , it has been installed and activated in the gamemaster module settings, but i dont know how to "popout", for example, a character sheet. I dont see any action button or menu in the sheet that i can press to have it in their own browser window :/

There is any trick that im missing to make it work? Im using Foundryvtt  v0.6.5 and Popout v0.8

**Comment by kakaroto** [comment]
When you enable the module, you'll have the popout button on the character sheet window decoration :
![image](https://user-images.githubusercontent.com/27990/89684361-41f73400-d8c8-11ea-9a8e-ade12cc00977.png)
