### ISSUE TITLE
Any way to pop out into a window instead of a tab?

### ISSUE THREAD

**Issue by focalmatter** [kakaroto/fvtt-module-popout#23]
I don't know if it's behaving as intended or not, but the popouts show up as other tabs rather than small pop-up windows. Is there any way to get them to pop out into windows like the Roll20 popouts?

**Comment by kakaroto** [comment]
In the module settings :
![image](https://user-images.githubusercontent.com/27990/92858782-79279c00-f3c4-11ea-8354-cc38410c34c7.png)
