### ISSUE TITLE
PF2 - Bug - Compendium Browser Fails Loading 

### ISSUE THREAD

**Issue by justinroszko** [kakaroto/fvtt-module-popout#26]
Not sure if you're able to fix this since it's likely due to a specific system, but.....

When opening the Compendium Browser to add a feat, item, etc. There's a "Loader is Null" error.  Below is what the console says it going on in Firefox. 

![image](https://user-images.githubusercontent.com/48022089/93656897-f1611380-f9fb-11ea-8c1b-9021b0614125.png)

Below is what's happening in Chrome

![image](https://user-images.githubusercontent.com/48022089/93656994-94b22880-f9fc-11ea-878e-9ad79a76f76e.png)

From what I can tell, it's the system module isn't able to read the information it needs to properly load the compendiums.   If you need more information, let me know and I can spin something up to help with testing.

**Comment by kakaroto** [comment]
I'm not sure if you reported this here by mistake or if you meant "when the compendium browser is opened as a popout".
Regardless, I don't think there would be anything for me to do to get it fixed. If the pf2 devs can't fix it either, there's now an option for them to tell popout not to handle their window so it can't be popped out, and it should be fine that way.
