### ISSUE TITLE
DND5e: Popout dies when activating a spell with an AoE template attached

### ISSUE THREAD

**Issue by TheGiddyLimit** [kakaroto/fvtt-module-popout#3]
As title. The sheet will attempt to minimize on clicking the spell, which does strange things to the popout.

Repro steps:
- Create actor; add spell with e.g. sphere target area
- Popout actor
- Activate spell

Suggested fix: 
Inject a new minimize method, e.g. `sheet.minimize = () => { console.log("squashed minimize attempt"); }`

**Comment by kakaroto** [comment]
Thanks for the report. Will fix at my next iteration of popout.
